/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryStockIdRouteImport } from './routes/inventory.$stockId'

const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryStockIdRoute = InventoryStockIdRouteImport.update({
  id: '/$stockId',
  path: '/$stockId',
  getParentRoute: () => InventoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/inventory/$stockId': typeof InventoryStockIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/inventory/$stockId': typeof InventoryStockIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/inventory/$stockId': typeof InventoryStockIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/contact'
    | '/corporate'
    | '/inventory'
    | '/inventory/$stockId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers'
    | '/contact'
    | '/corporate'
    | '/inventory'
    | '/inventory/$stockId'
  id:
    | '__root__'
    | '/'
    | '/careers'
    | '/contact'
    | '/corporate'
    | '/inventory'
    | '/inventory/$stockId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  InventoryRoute: typeof InventoryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$stockId': {
      id: '/inventory/$stockId'
      path: '/$stockId'
      fullPath: '/inventory/$stockId'
      preLoaderRoute: typeof InventoryStockIdRouteImport
      parentRoute: typeof InventoryRoute
    }
  }
}

interface InventoryRouteChildren {
  InventoryStockIdRoute: typeof InventoryStockIdRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryStockIdRoute: InventoryStockIdRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  InventoryRoute: InventoryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
